version: '3.8'

services:
  app:
    build: .
    image: exemplo_mentoria
    restart: always
    volumes:
      - ./src:/app/src/
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - ENVIROMENT=LOCAL
